### ISSUE TITLE
AtmosphereJS: Why are there 2 packages pointing to this repo?

### ISSUE THREAD

**Issue by Anima-t3d** [serut/meteor-coverage#1]
I was wondering why there is a `lmieulet:meteor-coverage` and a `serutan:meteor-coverage` package?
Is there any difference? The serutan package is flagged and seems to be abandoned? However both point to this repo.

Links: 
- https://atmospherejs.com/lmieulet/meteor-coverage
- https://atmospherejs.com/serutan/meteor-coverage

**Comment by serut** [comment]
Yes this is correct ! The serutan one will be removed someday..

**Comment by serut** [comment]
I also unpublished the package, but it's not possible to remove it. How did you find the https://atmospherejs.com/serutan/meteor-coverage link ?

**Comment by Anima-t3d** [comment]
I found the link through google ;-)
