### ISSUE TITLE
CI occasionally fails test-coverage-app-full, but test-app works

### ISSUE THREAD

**Issue by noahsw** [serut/meteor-coverage#10]
I'm seeing my full-app tests fail occasionally in CI when I have coverage enabled. It only repros ~50% of the time and the actual failure comes from random tests. I updated my CircleCI to also run the full-app tests *without* coverage and it seems to pass more consistently.

See https://circleci.com/gh/league-wins-pool/league-wins-pool/459

## Expected Behavior

Tests should return the same results each time

## Current Behavior

Tests are flaky when coverage is enabled.

## Possible Solution

I can't figure out the root of the problem because the output is fairly obfuscated:
```
C: Full-app test of Pools Full-app test of Pools.records "before each" hook for "should display the teams with the worst pick quality in a single season" : failed
  http://localhost:4096/app/app.js?hash=7cbf4a249d4e7456abee2c6afbc504da2650d6d7:3379:61
http://localhost:4096/packages/meteor.js?hash=ae8b8affa9680bf9720bd8f7fa112f13a62f71c3:1105:27
tryCallOne@http://localhost:4096/packages/promise.js?hash=2d5b025794b9c9e54e5cf6bea71c642ef921a2ed:277:14
http://localhost:4096/packages/promise.js?hash=2d5b025794b9c9e54e5cf6bea71c642ef921a2ed:363:25
flush@http://localhost:4096/packages/promise.js?hash=2d5b025794b9c9e54e5cf6bea71c642ef921a2ed:514:33
run@http://localhost:4096/packages/modules.js?hash=834bf315cf60012e72ec8171efc34e8acd4dad5e:51247:19
drainQueue@http://localhost:4096/packages/modules.js?hash=834bf315cf60012e72ec8171efc34e8acd4dad5e:51217:45
```

## Steps to Reproduce (for bugs)

1. https://github.com/league-wins-pool/league-wins-pool/compare/0828c5829b55...c06be2603ef9

## Your Environment

https://github.com/league-wins-pool/league-wins-pool/blob/c06be2603ef9dcfd847fdb8277e2bcca57ae2bd9/circle.yml

**Comment by noahsw** [comment]
Hmm hang on. In this CI pass (https://circleci.com/gh/league-wins-pool/league-wins-pool/460), the coverage test passed but the non-coverage test failed. My tests my just be flaky overall :-(

**Comment by serut** [comment]
Ok no problem. But on this repository, which is quite simple,  I have all the time dependencies issues, some variables (chai ?)  are undefined. But now this repository is almost fully made of es6, its a lot cleaner. We'll figure it out this problem

**Comment by noahsw** [comment]
Nice. Let me know when you want me to give it a try!

**Comment by serut** [comment]
If you clone meteor app exemple, edit the CI script to run 10 times any test, you gonna see the limit ! 
And sorry for my grammar Im too tired after the rush I've made
