### ISSUE TITLE
`.coverage.json` ignored when testing package with spacejam and mocha

### ISSUE THREAD

**Issue by cgalvarez** [serut/meteor-coverage#17]
First of all, @serut thank you very much for you effort and for public release of this great package :wink:

## Expected Behavior

Given the meteor app root is COVERAGE_APP_FOLDER, when trying to get the coverage analysis for a meteor package `my-package` through any of the following commands (executed from COVERAGE_APP_FOLDER):

```shell
spacejam test-packages --driver-package practicalmeteor:mocha --coverage "out_html" packages/my-package
spacejam-mocha --coverage "out_html" packages/my-package
```

with a customized `.coverage.json` file in COVERAGE_APP_FOLDER (meteor app folder), it should be used to configure the package.

## Current Behavior

What currently happens is that the `.coverage.json` configuration is wrong: the package `lmieulet:meteor-coverage` always take the configuration from its file `conf/default-coverage.json` instead of the customized one. I've tried putting the `.coverage.json` file at `COVERAGE_APP_FOLDER/.coverage.json` and `COVERAGE_APP_FOLDER/packages/my-package/.coverage.json`, with no success.

## Possible Solution

No idea if this is an issue of `lmieulet:meteor-coverage` or `serut/spacejam`. Just started trying with this package and still looking into the code.

## Steps to Reproduce

1. Place any package inside your meteor app subfolder `packages/package-to-test`.
2. Place any customized `.coverage.json` file in your meteor app (COVERAGE_APP_FOLDER).
3. Run any of the commands in the section **Expected Behavior** setting the environment variable `COVERAGE_VERBOSE=1`:

   ```shell
   COVERAGE_VERBOSE=1 spacejam test-packages --driver-package practicalmeteor:mocha --coverage "out_html" packages/my-package
   COVERAGE_VERBOSE=1 spacejam-mocha --coverage "out_html" packages/my-package
   ```

4. Check the wrong configuration at the very beginning of the verbose output: `Coverage configuration: .coverage.json values:`.

## Context

I was trying to customize the included/excluded patterns for my meteor app, so I created my customized `.coverage.json` file which it is currently being ignored.

## Your Environment

- Versions used:
   - meteor@1.4.1.1
   - lmieulet:meteor-coverage@0.9.4
   - practicalmeteor:mocha@2.4.5_6
   - spacejam: https://github.com/serut/spacejam/tarball/windows-suppport-rc4
- Environment name and version: Node.js v6.3.1
- Operating System and version: Ubuntu Desktop 16.04

**Comment by cgalvarez** [comment]
Just found the problem: an *extra* comma in the `.coverage.json` wich made it a malformed JSON.

I think the package could be improved by warning the user when the customized `.coverage.json` is malformed. I'll make a PR about this. Closing the issue.

**Comment by serut** [comment]
You're totally right, the package shall warn you when the file exists but cannot be parsed. 

- [ ] raise a console.error if the files is not valid, with the corresponding stack trace
- [ ] use default config anyway

Thanks for your future pull request !
