### ISSUE TITLE
Output folder is not automatically created for the report type `out_coverage`

### ISSUE THREAD

**Issue by cgalvarez** [serut/meteor-coverage#19]
## Expected Behavior

As a user, I expect the output folder specified in my customized `.coverage.json` (key `output`) to be automatically created for the requested report type `out_coverage`.

## Current Behavior

What really happens is that the output folder is not created for the report types `out_coverage` and the following exception trace is printed to the terminal, warning the user about the impossibility of saving the report results due to inexistent path:

```shell
W20160907-12:49:59.731(2)? (STDERR) /tmp/meteor-test-rundxuvs9/.meteor/local/build/programs/server/packages/lmieulet_meteor-coverage.js:539
W20160907-12:49:59.731(2)? (STDERR)         throw 'failed to write report file: ' + reportPath;                                                            // 17
W20160907-12:49:59.732(2)? (STDERR)         ^
W20160907-12:49:59.732(2)? (STDERR) failed to write report file: /home/user/my-meteor-app/packages/my-package/coverage/report.json
```

This error could be concealed by calling any of the previous two report types before or by manually creating the output folder like in the package `circle.yml` or `.travis.yml` files.

I suppose automatically creating output folder is the expected behavior or not, since it's what happens with all other report types (except `out_text_summary`, which does not work, as I've reported in #20).

## Possible Solution

I think the most efficient way to do this is checking for the existence of the output folder (whether if it's customized or not) once for all reports, since it is usual for them to create an output file (if any of them needs to create additional folders like the HTML reporter, then it should check for those subfolders specifically).

I need someone pointing me in the right direction to make a PR for this. I think `ReportCommon.checkDirectory()` should be invoked (which synchronously creates the folder if cannot stat it) before calling any of the available reporters, but don't know where to best place it.

## Steps to Reproduce (for bugs)

Execute any of the following codes with non-existent output folder:

```shell
spacejam test-packages --driver-package practicalmeteor:mocha --coverage out_coverage packages/my-package
spacejam-mocha --coverage out_coverage packages/my-package
```

## Context

I was trying to change the output folder and try all the implemented/available report types.

## Your Environment

- Versions used:
   - meteor@1.4.1.1
   - lmieulet:meteor-coverage@0.9.4
   - practicalmeteor:mocha@2.4.5_6
   - spacejam: https://github.com/serut/spacejam/tarball/windows-suppport-rc4
- Environment name and version: Node.js v6.3.1
- Operating System and version: Ubuntu Xenial Desktop 16.04

**Comment by cgalvarez** [comment]
I've rewritten the title and description of this issue to separate into two different issues, to improve traceability of the problems. Sorry for the incovenience.

**Comment by serut** [comment]
I think it can be done on startup, on that file : https://github.com/serut/meteor-coverage/blob/master/server/main.js
Maybe extract L8 to L11 of `main.js` inside a new class `boot.js` ?
In that context, it's possible to create the directory using the async interface instead of what do `ReportCommon.checkDirectory()` to gain few ms

**Comment by cgalvarez** [comment]
Thank you very much for your insights. Taking a look at them and working in the PR.

BTW, just a quick tip if don't know it: you can preselect lines of GitHub files like [this](https://github.com/serut/meteor-coverage/blob/master/server/main.js#L8-L11), so you don't have to take care of the line numbers (just click the line you want to highlight, and if you want a range of them, just hold `shift` and make a second click on the last line).
