### ISSUE TITLE
exportCoverage

### ISSUE THREAD

**Issue by Heinerion** [serut/meteor-coverage#2]
I'm sorry, but I don't understand how to export the coverage.

You wrote:

> Run the following command in your browser and the client coverage will be saved into the server

I guess the same should be true for the following two Methods, but all I get is `Uncaught ReferenceError: Meteor is not defined`  
How am I supposed to trigger the export?

Thanks in advance, 
Heinerion

**EDIT**
If I use the route `http://localhost:3070/coverage/export/lcovonly`, my only result is a `Thanks !` on the screen.

**Comment by Heinerion** [comment]
Sorry, I found the files in the `COVERAGE_APP_FOLDER`. I expected something like a file download.

**Comment by serut** [comment]
Yes ! anyway the file file.lcov is not readable by human ... https://github.com/practicalmeteor/spacejam/pull/59 if you want to know how it will be implemented soon.
Or look at this working project exemple: https://github.com/serut/meteor-coverage-app-exemple

**Comment by Heinerion** [comment]
Thank you for the answer despite I already closed the ticket.  
I really appreciate that :)
