### ISSUE TITLE
Wrong report paths when testing packages from meteor app dir

### ISSUE THREAD

**Issue by cgalvarez** [serut/meteor-coverage#35]
## Expected Behavior

When testing packages from meteor app dir, the reports paths should refer to the `COVERAGE_APP_FOLDER`, which is the meteor app dir when testing packages from it.

## Current Behavior

All path inside reports `json_summary.json`, `summary.json` and `lcov.info` are relative to their respective packages, not the meteor app dir.

## Possible Solution

Working on the PR right now...

## Steps to Reproduce (for bugs)

1. Run `meteor-coverage-app-exemple$ meteor npm run coverage-packages-mocha`.
2. Check contents of `json_summary.json`, `summary.json` and/or `lcov.info` inside `.coverage/`.
3. Surprise! The first part (`packages/meteor-coverage`, `packages/somepkg`,...) of all relative paths has been stripped for every path in those files, so you don't know which package each file belongs to (and all paths are unaccessible per se, of course, because they should be relative to `COVERAGE_APP_FOLDER`, `meteor-coverage-app-exemple` in this case, instead of being relative to the package folder that file belongs to).

I've just noticed it while testing the rewrite of PR #29 with `serut/meteor-coverage-app-exemple` because `remap-istanbul` is feeded with `summary.json` and it can't find the referenced files.

AFAIK HTML report, `summary.txt` and `report.json` are not affected by this issue. This seems to need another PR... I think the best is fixing each affected report in its own file righ after they've been generated and **only** when testing packages from meteor app-dir.

## Context

I was trying to get rewrite of PR #29 passing the tests.

## Your Environment

- Versions used:
   - meteor@1.4.1.1
   - lmieulet:meteor-coverage@dev-1.0.0
   - practicalmeteor:mocha@2.4.5_6
   - spacejam: https://github.com/serut/spacejam/tarball/windows-suppport-rc4
- Environment name and version: Node.js v6.3.1
- Operating System and version: Ubuntu Xenial Desktop 16.04

**Comment by serut** [comment]
Is it related to https://github.com/serut/meteor-coverage/blob/master/server/report/report-generic.js#L39-L44 ?

**Comment by serut** [comment]
Yes it's that.

**Comment by cgalvarez** [comment]
Yes, I've already fixed it. PR is on the way...

**Comment by cgalvarez** [comment]
And this has made rewrite of #29 pass the `meteor-coverage-app-exemple` tests, so wait a group of pull requests :grin: in short time :stuck_out_tongue_winking_eye: !

**Comment by serut** [comment]
😨  rebase on the current state of dev-1.0.0, I've just pushed my commit

**Comment by cgalvarez** [comment]
I was reviewing your commit right now. Don't worry, I'll do it. Thanks for letting me know :blush:

**Comment by cgalvarez** [comment]
Fixed on [commit](https://github.com/serut/meteor-coverage/pull/30/commits/a970c3f00d6fdccad841e3f04bc45049589b02d6).
