### ISSUE TITLE
Use relative coverage_app_folder

### ISSUE THREAD

**Issue by HugoHeneault** [serut/meteor-coverage#40]
Multiple devs may use different folders on their computers. Currently, the `coverage_app_folder` is an absolute path.

## Possible Solution
Use a relative path, or no path at all : meteor could send its path via a method?

**Comment by serut** [comment]
That path isn't provided by Meteor, can't be relative, and is used a lot of times in our package. 

If you are using git, you can do the following:
- commit the configuration file one time.
- add the file to the `gitignore` file
- ask to other devs to edit the path before running coverage locally
- on the CI platform, use spacejam, it retrieve that path by itself
