### ISSUE TITLE
`Altered source could not be accessed:` error and no coverage generated

### ISSUE THREAD

**Issue by elenadimitrova** [serut/meteor-coverage#44]
Moving issue from https://github.com/practicalmeteor/spacejam/issues/69

Fails to generate code coverage

## Expected Behavior
spacejam test --driver-package practicalmeteor:mocha-console-runner --coverage out_coverage

where .coverage.json is 

```
{
  "include": [],
  "exclude": {
    "general": [
      "/**/packages/**/*",
      "../**/packages/**/*",
      "/**/contracts/**/*",
      "/**/lib/test/**/*",
      "/**/*stream*.js",
      "/**/tests/**/*",
      "**/*test.js",
      "/**/*test.js"
    ],
    "server": [
      "/**/lib/test/**/*",
      "/**/server/test/**/*",
      "/**/tests/**/*"
    ],
    "client": [
      "/**/client/**/containers/**/*.js",
      "/**/client/**/mixins/**/*.js",
      "/**/client/**/components/**/*.js",
      "/**/client/**/components/**/*.jsx",
      "/**/client/**/composers/**/*.js",
      "/**/client/**/test/**/*.js",
      "/**/client/**/tests/**/*.js",
      "/**/client/test/**/*.js",
      "/**/*.jsx",
      "/**/client/stylesheets/**/*"
    ]
  },
  "output": "./.coverage"
}
```

should produce a `COVERAGE_APP_FOLDER/.coverage/report.json` coverage dump

## Current Behavior
Running
`spacejam test --driver-package practicalmeteor:mocha-console-runner --coverage out_coverage`
does not produce a coverage dump and shows the following error
```
W20161018-14:20:49.329(3)? (STDERR) Error: COVERAGE_APP_FOLDER is undefined and the coverage will fail.
```

Running 
`COVERAGE=1 COVERAGE_APP_FOLDER=./ spacejam test --driver-package practicalmeteor:mocha-console-runner --coverage out_coverage`
does not produce a coverage dump and shows a number of "Altered source could not be accessed: " errors:
```
W20161018-14:22:30.133(3)? (STDERR) Cannot access client/imports/modules/core/actions/target.js
W20161018-14:22:30.134(3)? (STDERR) Altered source could not be accessed: meteor://💻app/client/imports/modules/core/actions/target.js
```

## Your Environment
* Version used: 
lmieulet:meteor-coverage 1.1.3
spacejam@1.6.2-rc.4
* Environment name and version (e.g. Node 0.10.47): 
node v6.8.1
npm v3.10.9
* Operating System and version:
OSX Sierra v10.12 (16A323)

**Comment by serut** [comment]
Can you try without providing the `--driver-package` ?

**Comment by serut** [comment]
And you are not using the right version of spacejam !

`meteor npm i --save-dev https://github.com/serut/spacejam/tarball/windows-suppport-rc4`

**Comment by elenadimitrova** [comment]
Thanks, the spacejam version update solved it. 

A separate question before we close the issue, is there a way to generate detailed coverage for the app, showing not just the high level ../web/browser/app coverage but going down to each file level?

**Comment by serut** [comment]
Where do you see `../web/browser/app` ? Can you provide the corresponding screenshot ?

If you use sonar (private repo) or codecov (public repo) you can map the coverage to files using the lcov file, to get a nice report like https://codecov.io/gh/serut/meteor-coverage. If you don't have, use the html export to create a static coverage report. There is 4 differents HTML report format provided by istanbul but only the current one is working.

**Comment by elenadimitrova** [comment]
Yes, we're using `istanbul` to report on the coverage like this:

![screen shot 2016-10-18 at 14 51 02](https://cloud.githubusercontent.com/assets/703848/19476549/6f997724-9542-11e6-9262-1f2c9d573b8e.png)

which we'd like to expand out to show detailed coverage for each file of the app

**Comment by serut** [comment]
Looks like istanbul doesn't get the coverage remapped to correct files.

**Comment by elenadimitrova** [comment]
The `text_summary` option just gives us the coverage summary

```
=============================== Coverage summary =====
Statements   : 56.72% ( 1139/2008 )
Branches     : 34.35% ( 372/1083 )
Functions    : 55.77% ( 227/407 )
Lines        : 58.37% ( 1091/1869 )
========================================================================
```

**Comment by serut** [comment]
Try `out_json_report` and `out_html`

**Comment by elenadimitrova** [comment]
Both of these do the job of showing the details, thanks!

**Comment by grsabreu** [comment]
Awesome thread

**Comment by elenadimitrova** [comment]
@serut our meteor coverage dropped 11% because client-side meteor tests are not run but just server side ones. Any ideas why this maybe happening?

**Comment by serut** [comment]
- meteor-coverage is agnostic if launch your app in test mode or not.

you say client side tests are not run ? Or you just don't see the client coverage on your report ?

**Comment by grsabreu** [comment]
Also not getting my client side tests running here and I'm getting this at the end:

```
Tests are ok! Meteor-coverage is saving client side coverage to the server. Client js files saved  {"SUCCESS":2,"FAILED":0,"TOTAL":2}
coverage error: Failed to save lcovonly coverage
spacejam: phantomjs exited with code: 7
spacejam: killing meteor
spacejam: meteor killed with signal: SIGTERM
spacejam: Unknown error with exit code '7'. Exiting.
```

How I run:
`spacejam test --coverage 'out_lcovonly out_coverage out_html' --driver-package practicalmeteor:mocha-console-runner`

**Comment by serut** [comment]
@grsabreu  This is not the same issue. Feel free to open your own issue. It looks like your .coverage folder does not exist, maybe post a dump with `COVERAGE_VERBOSE=1 spacejam  [..]`

**Comment by serut** [comment]
@elenadimitrova I also need a dump with coverage verbose, if you see a line that looks like `Tests are ok! Meteor-coverage is saving client side coverage to the server. Client js files saved  {"SUCCESS":2,"FAILED":0,"TOTAL":2}` ...

**Comment by elenadimitrova** [comment]
When we run `./node_modules/.bin/spacejam test --driver-package practicalmeteor:mocha-console-runner --coverage 'out_json_report' COVERAGE_VERBOSE=1` we get

```
spacejam: spawning meteor
[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
spacejam: meteor mongodb is ready
=> A patch (Meteor 1.4.1.2) for your current release is available!
   Update this project now with 'meteor update --patch'.
W20161019-21:39:16.040(3)? (STDERR) Module load hook: transform [/private/var/folders/41/y_3bjvkj19b54sp51dzk63vh0000gn/T/meteor-test-run1fr6nyr/.meteor/local/build/programs/server/app/app.js]
I20161019-21:39:21.360(3)? Kadira: completed instrumenting the app
=> Started your app.

=> App running at: http://localhost:4096/
spacejam: meteor is ready
spacejam: spawning phantomjs
phantomjs: Running tests at http://localhost:4096/local using test-in-console and coverage
I20161019-21:39:29.508(3)? MochaRunner.runServerTests: Starting server side tests with run id 97F8Xjf5A6kjnK8dR
W20161019-21:39:29.717(3)? (STDERR) { type: 'TEST' }
W20161019-21:39:29.717(3)? (STDERR) { type: 'TEST' }
W20161019-21:39:29.725(3)? (STDERR) { type: 'TEST', data: { tests: 'to test all the things' } }
W20161019-21:39:29.783(3)? (STDERR) No getter registered for boo
W20161019-21:39:29.784(3)? (STDERR) No getter registered for boo
W20161019-21:39:29.784(3)? (STDERR) No getter registered for boo
W20161019-21:39:29.785(3)? (STDERR) No getter registered for boo
W20161019-21:39:29.785(3)? (STDERR) No getter registered for buu
W20161019-21:39:30.442(3)? (STDERR) { [Error: child "cardId" fails because ["cardId" is required] [validation-error]]
W20161019-21:39:30.443(3)? (STDERR)   error: 'validation-error',
W20161019-21:39:30.444(3)? (STDERR)   reason: 'child "cardId" fails because ["cardId" is required]',
W20161019-21:39:31.973(3)? (STDERR) MochaRunner.runServerTests: failures: 0
Tests are ok! Meteor-coverage is saving client side coverage to the server. Client js files saved  {"SUCCESS":1,"FAILED":0,"TOTAL":1}
spacejam: phantomjs exited with code: 0
spacejam: killing meteor
spacejam: meteor killed with signal: SIGTERM
spacejam: All tests have passed. Exiting.
``` 

And when I run `meteor test --driver-package dispatch:mocha-browser` the client side tests are not run too as the test results there clearly show it.

**Comment by grsabreu** [comment]
Ok, @serut. I just felt it could be the same because I also have some client tests and they aren't getting executed.
Anyway, I'm going to open a new issue. Thanks!

**Comment by serut** [comment]
@elenadimitrova 
- Can you send me your application structure or a reproduceable environment ? 
- What your test look like ? The last that I did is this one https://github.com/apollostack/meteor-starter-kit/compare/master...serut:master#diff-e0e6f0b65bda89a32a9126805f2c882bR1
- if you don't see any client test, you can run your app in watch mode, the recompilation between each edition is far more faster.

**Comment by elenadimitrova** [comment]
@serut when I ran spacejam against the meteor-starter-kit app it still gives only 1 (of expected 2 for both server and client) test suites succeed

`Tests are ok! Meteor-coverage is saving client side coverage to the server. Client js files saved  {"SUCCESS":1,"FAILED":0,"TOTAL":1}`

The structure of the app, as far as tests are concerned is as follows

```
./app
├── client                  
│   ├─── imports 
│   |   ├── module 
│   |   |	└── moduleA 
│   |   |	   └── tests
│   |   |	└── moduleB 
│   |   |	   └── tests
│   |   |	└── moduleC 
│   |   |	   └── tests          
│   └── test             
├── lib                 
│   └── test            
└── server     
    ├─── lib         
    ├─── methods 
    ├─── publications    
    └── test
```

**Comment by serut** [comment]
No that line means that there is one file instrumented on the client side that have been sent to the client

**Comment by elenadimitrova** [comment]
I'm just running `meteor test` with the different possible driver packages to help troubleshoot this. results below.

`practicalmeteor:mocha`  - Should runs client and server package or app tests and display all results in a browser. 
Only server tests run. Client test list in browser shows empty.

`dispatch:mocha-phantomjs` Should run client and server package or app tests using PhantomJS and report all results in the server console.
Both client and server tests run in console but tests cycle stuck in an endless loop running the tests.

`dispatch:mocha-browser` shoupld run client and server package or app tests with Mocha reporting client results in a web browser and server results in the server console.
This shows the correct tests in server and browser.

I wonder if this is related to the symptom above of running with `practicalmeteor:mocha` driver?

**Comment by elenadimitrova** [comment]
One of the issues with output was fixed by upgrading practicalmeteor:mocha to 2.4.5_6 (see #42)

Now I can _actually_ see the test output in the console when I run spacejam which confirms that both client AND server tests are run but not all client files are included in the coverage.

```
./app
├── client                  
│   ├─── imports 
│   |   ├── module 
│   |   |	├── moduleA 
│   |   |	|  ├── actions           # This IS included in coverage
│   |   |	|  ├── **components**  # This is NOT included in coverage
│   |   |	|  ├── **containers**     # This is NOT included in coverage
│   |   |	|  └── tests
│   |   |	├── moduleB 
│   |   |	|  ├── actions           # This IS included in coverage
│   |   |	|  ├── **components**  # This is NOT included in coverage
│   |   |	|  ├── **containers**     # This is NOT included in coverage
│   |   |	|  └── tests
│   |   |	├── moduleC 
│   |   |	|  ├── actions           # This IS included in coverage
│   |   |	|  ├── **components**  # This is NOT included in coverage
│   |   |	|  ├── **containers**     # This is NOT included in coverage
│   |   |	|  └── tests   
│   |   |	└── lib    
│   └── test             
├── lib                                      # This IS included in coverage
│   └── test            
└── server     
    ├─── lib                               # This IS included in coverage
    ├─── methods                    # This IS included in coverage
    ├─── publications               # This IS included in coverage
    └── test
```

**Comment by elenadimitrova** [comment]
One of the issues with output was fixed by upgrading practicalmeteor:mocha to 2.4.5_6 (see #42)

Now I can _actually_ see the test output in the console when I run spacejam which confirms that both client **and** server tests are run but not all client files are included in the coverage report. Note that the results from the ./app/client/imports/modules/moduleX/test are not included in coverage. Test from all other locations are.

```
./app
├── client                  
│   ├─── imports 
│       ├── modules 
│       |	├── moduleA        
│       |	|  └── tests        # Test results from here are NOT included in coverage
│       |	├── moduleB         
│       |	|  └── tests        # Test results from here are NOT included in coverage
│       |	├── moduleC             
│       |	|  └── tests        # Test results from here are NOT included in coverage   
│       |	└── lib    
│      └── test             
├── lib                                              
│   └── test            
└── server     
    ├─── lib                                       
    ├─── methods                            
    ├─── publications                      
    └── test
```

**Comment by elenadimitrova** [comment]
One of the issues with output was fixed by upgrading `practicalmeteor:mocha to 2.4.5_6` (see #42)

Now I can _actually_ see the test output in the console when I run spacejam which confirms that both client **and** server tests are run, so that is not the problem.

I have found the inconsistency in the code coverage results is coming from the different type of reports. Steps to reproduce:

Runt the following to produce a report.json (from `out_coverage` option) and summary.json (from `out_json_report` option)
`spacejam test --driver-package practicalmeteor:mocha-console-runner --coverage 'out_coverage, out_json_report'`

Then I used istanbul to visualise these for easier reading but you can see when using the `out_coverage` option result I get 45% and `out_json_report` gives back 34%

![screen shot 2016-10-20 at 18 23 57](https://cloud.githubusercontent.com/assets/703848/19566295/6d97a534-96f2-11e6-8943-f0ff696b0275.png)

Am I making a mistake somewhere? This is very strange.

**Comment by serut** [comment]
I don't think your app contains 11621 lines of code. The report.json contents all your app coverage and dependencies coverage whereas summary.json filtrate every file entry and should contains only your app coverage.

**Comment by serut** [comment]
Nice catch otherwise @elenadimitrova ! ;-)

**Comment by elenadimitrova** [comment]
Thanks for all your help! :)
