### ISSUE TITLE
Coverage not finding SOME of my files

### ISSUE THREAD

**Issue by hexsprite** [serut/meteor-coverage#47]
## Expected Behavior

That all the source files being referenced during tests will show up.
## Current Behavior

Only some of the files being used are showing up.

They are definitely being used during the tests but they do not appear in the coverage report.

For example, in this case I have a base class that is used by two other classes.  The two subclasses are not showing up but the base class is showing coverage.

Since I don't use the base class by itself that is showing that the subclasses are being referenced.

I should note these are CoffeeScript files. I don't know if this package is certified to work with that.

SOME Coffeescript files show up, but some do not.
## Steps to Reproduce (for bugs)

I can try to create a repo when I have a bit more time but if any diagnostic steps or ideas come to mind they would be appreciated.
## Your Environment
- Version used: latest version of meteor-coverage
- Environment name and version (e.g. Node 0.10.47): Meteor 1.4.1.3 and Meteor 1.4.2.1 beta 1
- Operating System and version: MacOS Sierra 10.12.1

**Comment by hexsprite** [comment]
I just converted one of the missing classes over to Javascript. Now it shows up in the report properly.

**Comment by serut** [comment]
> Only some of the files being used are showing up.

By default, when you run `meteor test`, only required files are bundled, so we can't see the 0% of coverage on that files. Either they are not required either they have been ignored.    
If you want to help with this issue, can you create a reproduceable environment or fork with the reproducable bug my repo meteor-coverage-app-exemple ?
I'm also interested to get the log with all info (verbose=1) to see if yours files are ignored or not.

**Comment by grsabreu** [comment]
@hexsprite I could solve that issue by running the meteor test with the `--full-app` flag so all the files would be loaded for the coverage
