### ISSUE TITLE
Specifying Coverage Report location

### ISSUE THREAD

**Issue by zenweasel** [serut/meteor-coverage#5]
Sorry if this is an obvious question but I am unable to figure this out. When I run my test suite the HTML coverage report is sent to the console but I do not see a report anywhere or how to specify where it should be output to. I can't use the console output since it's wrapped in log messages.
`I20160705-06:34:57.338(8)? <!DOCTYPE html><html><head><title>Coverage</title><meta charset="utf-8"><script>`

I have `COVERAGE_APP_FOLDER` pointed to a local `.coverage` directory, but that doesn't seem to affect anything.

**Comment by serut** [comment]
Hey ! If you want to see the HTML report, you need to go to `localhost:3000/coverage`. There are no other way to see an human readable report.   
The `COVERAGE_APP_FOLDER` must point the root folder of your app as it is described in the readme. When you export the lcov report, it writes the file inside at `COVERAGE_APP_FOLDER` + `lcov.info`
Hope this will help you, otherwhise can you tell me how do you launch your test suite and what was you expecting ?

**Comment by zenweasel** [comment]
I am running this in CI and was hoping that this would output an HTML/JSON file that could be viewed and analyzed separately (this is what I am used to with other coverage tools).

**Comment by serut** [comment]
It's not perfect, but you can give a try to `spacejam` + `practicalmeteor:mocha-console-runner`, here is the script to run tests on CI and save coverage in a `lcov` file : 
https://github.com/serut/meteor-coverage-app-exemple/blob/using-spacejam-windows/circle.yml 
I've created a fork of spacejam that runs tests and save the coverage. The fork can be installed using `npm install -g https://github.com/serut/spacejam/tarball/windows-suppport-rc4`.   

If you want to see the coverage in HTML files for example, it requires to implement the html format  : https://github.com/serut/meteor-coverage#meteorexportcoveragetype-callback

However, I still have some issues on CI: 
- cannot save coverage when running test-packages inside a meteor app
- still some random issues with undefined object while spacejam launch the phantomjs runner: 
````
# I20160708-16:04:29.809(0)? registerSourceMap../web.browser/app/app.js
# I20160708-16:04:29.810(0)? Add source map for file ../web.browser/app/app.js.map
# I20160708-16:04:29.810(0)? registerSourceMap../web.browser/app/app.js
# phantomjs: Error: Cannot find module 'meteor/practicalmeteor:mocha/meteor/src/index.js'
#     http://localhost:4096/packages/modules-runtime.js?hash=b7370236eeaf57e8f4ac703424bc831028392451: 439
# or
# phantomjs: TypeError: undefined is not an object (evaluating 'Package['practicalmeteor:chai'].chai')
#     http://localhost:4096/packages/practicalmeteor_sinon.js?hash=d51f09b72f5e645e87a6101ca90a5e06f108616d: 1
#or
#phantomjs: TypeError: undefined is not an object (evaluating 'Package['practicalmeteor:loglevel'].loglevel')
#    http://localhost:4096/packages/practicalmeteor_mocha.js?hash=0c7bae1a756c9691267ec935a8d6a4e081df9cf6: 9

```

**Comment by serut** [comment]
You can now define in the `.coverage.json` the output path
And you can export the coverage report (using spacejam) into html files, so I close the issue ! ;-)
