### ISSUE TITLE
coverage package adds junk to test output

### ISSUE THREAD

**Issue by Pushplaybang** [serut/meteor-coverage#50]
using this package adds a bunch of additional text to the test output, making it difficult to read.

## Expected Behavior
it shouldn't 

## Current Behavior
Its text through out the tests:

```js
‣
++cov_27jg3ehowk.f[118];// 7
var order=(++cov_27jg3ehowk.s[279],{// 8
orderId:'OI1001',// 9
```

## Steps to Reproduce (for bugs)

I'm running tests locally with:

```sh
cd app/ && meteor test --full-app --driver-package practicalmeteor:mocha --port 7357 --settings settings/settings-test.json
```

and on CI with:

```sh
cd app/ && spacejam test --full-app --once --settings settings/settings-test.json --driver-package practicalmeteor:mocha-console-runner --port 7357
```
Let me know if you need more info.  Cheers.

**Comment by serut** [comment]
```
‣
++cov_27jg3ehowk.f[118];// 7
var order=(++cov_27jg3ehowk.s[279],{// 8
orderId:'OI1001',// 9
```
Can you share the code producing such output ?   

On the last repository I've created (meteor + react + apollo & coverage), I do not see any excessive log : look at the CI output https://travis-ci.org/serut/meteor-react-apollo-test-coverage-starter-kit#L498 and let me know if it's indecent.

On my project I'm working on, we test and we run the test app with coverage in two different subprocess,  to let us see at the test report without any coverage stuff, which is quite enough complicated..

**Comment by Pushplaybang** [comment]
Hi Serut,

This seems to be happening with hte mocha browser reports using `practiclemeteor:mocha`.

the packages I'm using include:

```sh
dburles:factory@1.1.0
lmieulet:meteor-coverage@1.1.4
practicalmeteor:chai@2.1.0_1
practicalmeteor:mocha@2.4.5_5
practicalmeteor:mocha-console-runner@0.2.3
practicalmeteor:mocha-core@1.0.1
practicalmeteor:sinon@1.14.1_2
tmeasday:acceptance-test-driver@0.1.0
tmeasday:test-reporter-helpers@0.2.1
```
and this seems to appear in the console when tests fail.

Screenshot from browser reporter:

<img width="573" alt="screen shot 2017-05-01 at 4 06 14 pm" src="https://cloud.githubusercontent.com/assets/1330359/25581463/4315af12-2e88-11e7-9de3-ca3cf17d249a.png">

**Comment by serut** [comment]
You should not use practicalmeteor:mocha@2.4.5_5, the 2.4.5_6 is the best one. (cf the readme of my package) 

You see directly the code instrumented with the global variable incremented each time your algorithm pass through the code. Its mandatory to collect the coverage. If you run in test mode do you see lines number on the right ?

**Comment by Pushplaybang** [comment]
Hi @serut 

Thanks, but as I've commented on your PR, upgrading breaks my tests with space jam which I'm of course using for CI.  

So are you suggesting this linked to 2.4.5_5 ?

**Comment by serut** [comment]
Hey ! This issue is outdated as I don't recommend anymore to use `practicalmeteor` dependencies on Meteor 1.6.
