### ISSUE TITLE
Not Instrumenting all files

### ISSUE THREAD

**Issue by singhsoldier13** [serut/meteor-coverage#51]
I am running "COVERAGE_APP_FOLDER=$(pwd)/ COVERAGE_VERBOSE=1 COVERAGE=1 spacejam test --coverage 'out_lcovonly out_coverage out_html out_remap' --driver-package practicalmeteor:mocha-console-runner" to generate coverage.

It does generate coverage information but it does not instruments all the files. Only those files are istrumented which are used by tests.
In the past, I have used nyc/istanbul for coverage and I have to use --all option to instrument all files.

**Comment by serut** [comment]
Yes, if you do not import a file then it's not bundled on the test app. This implementation will never be able to instrument all files automatically, sorry.

**Comment by singhsoldier13** [comment]
Okay. Let's say I have total 100 files in src and I wrote few unit tests for 2 files. Code's Line coverage definition is Total Code Lines/Covered Lines. If we can't achieve that, it means we are not calculating coverage properly.
Initially, I was using NYC (internally uses Istanbul) with Mocha to get coverage but it had issues resolving meteor's packages. I was able to instrument all files using --all command line option (check [).](https://github.com/istanbuljs/nyc#use-the---all-flag-to-include-files-that-have-not-been-required-in-your-tests) Could you check if Istanbul API provides such option? If yes, we can wire it through .coverage.json file. Let me know what your thoughts are and thanks very much for looking at this.

**Comment by serut** [comment]
I'm already doing what you are expecting, the --all is the native behavior of my lib.

When meteor builds the test app, it first grabs all dependencies like jquery, utils, ... and even my lib. It creates kind of foundation where your app run. My lib, when it is executed, changes the behavior of node `runInThisContext`. Now every imports automatically instrument the file before executing it. Which means that every code called after my lib was executed will be instrumented. (instrumented = coverage stuff/stats saved in a global variable)  
The compilator then build your test app by importing every tests files that matches some kind of regex (let's say **/*.test.js), which means that if a file is imported the compilator will import all its dependencies. 

It doesn't bundle all your app, just was is required from yours test files.

**Comment by singhsoldier13** [comment]
I was looking into istanbuljs-api package yesterday and I noticed that they added a step to instrument "missing" files that were not imported in the test files (refer to "run-cover.js" in istanbuljs-api). Without that step, they produce same output as your package is doing. Can we add similar step?

**Comment by serut** [comment]
I don't think so... And I have a lot of work right I can't update meteor-coverage for now

But did you tryed to execute your app in `--full-app` ? In that mode all files are bundled before test are executed.

And I think sonar/coveralls/.. scan your real app, but coverage where it sees coverage and show you global stats. Html output is not so great

**Comment by singhsoldier13** [comment]
Alight, I will keep exploring some ideas and if I can fix it, will create a PR to your repo. Thanks for your help 👍
