### ISSUE TITLE
Empty Coverage folder but works with windows-suppport-rc4

### ISSUE THREAD

**Issue by singhsoldier13** [serut/meteor-coverage#52]
On OSX when I run coverage using spacejam, .coverage folder is created but has no files in it. When I switched to https://github.com/serut/spacejam/tarball/windows-suppport-rc4, it generates report and instrumented files. (Although it does not include all files under instrumentation, refer to issue #51 )

**Comment by serut** [comment]
I don't follow you. I've created a fork of spacejam that supports coverage, and yes the original spacejam does not support coverage. Is it what you are looking for ?

**Comment by singhsoldier13** [comment]
Oh okay, I didn't realize that your spacejam's fork has coverage options, not the original one. Thanks for clearing that up.
