### ISSUE TITLE
No server-side coverage since Meteor 1.6 recorded

### ISSUE THREAD

**Issue by SimonSimCity** [serut/meteor-coverage#54]
I have a project, where I use this plugin here to generate code-coverage. Today I tried to update to Meteor 1.6, which worked perfect and all my tests ran through, but the code-coverage only showed the lines as covered which are included in the code, run on the client (browser), but not those lines run on the server.

I called it by the following command:

    spacejam-mocha test --settings settings-test.json --coverage 'out_json_report out_coverage'

I use `lmieulet:meteor-coverage` in version `1.1.4` and just switched Meteor from `1.5.2.1` to `1.6-rc.17`.

**Comment by SimonSimCity** [comment]
Could confirm it by calling:

    COVERAGE_VERBOSE=1 COVERAGE=1 COVERAGE_APP_FOLDER=$(pwd)/ meteor

If the project is running on `meteor 1.5.2.1` I see a lot of `[Ignored][exclude.server]` lines at the beginning for all the js files from the `/packages/` folder. When upgrading to `meteor 1.6-rc.17` I don't see these ignores anymore.

**Comment by serut** [comment]
They may have change the way they are processing server files before starting the server. You don't have any clue except that some logs are missing

**Comment by SimonSimCity** [comment]
Nope, but I'll have to dig into it if you don't have time to fix it. Any help and details about how it works is appreciated ...

All I know is, that they switched from NodeJS 4.x.x to NodeJS 8.8.0. Maybe this had an impact on it. Maybe NodeJS introduced something, which could be solved by updating the `Istanbul` plugin - which is the first thing I'd give a try.

**Comment by serut** [comment]
On the node side, when `meteor-coverage` is imported by meteor, any module loaded after that will be covered. `meteor-coverage` asks istanbul to catch all call to [vm.runInThisContext](
https://nodejs.org/api/vm.html#vm_vm_runinthiscontext_code_options), a (very low level) function used to require a file (jquery, react, your app,..) from the current one. It alters the function globally, so when some code in your app `import 'something'`, it basically calls `vm.runInThisContext` which is a hook now `meteor-coverage` have been executed.

`meteor-coverage` execute that in the file [server/services/instrumenter.js:L29-35](https://github.com/serut/meteor-coverage/blob/master/server/services/instrumenter.js#L29-L35).  

I've created a function that is called everytimes istanbul received a call by node, to decide if the file should be instrumented or not. Just add a log inside the function [shallInstrumentServerScript](https://github.com/serut/meteor-coverage/blob/master/server/services/instrumenter.js#L110). 

If you have nothing, something changed with node V8 !

To let you test what I propose you, you need to clone my library in your `<app folder>/packages` directory ([example](https://github.com/serut/meteor-coverage-app-exemple/tree/master/packages)). Once cloned, meteor detects that the package can be retrieved in your `<app folder>/packages` and not in the _meteor central folder_ where modules are stored. 

Good luck ! If you want to upgrade istanbul you can look if the

**Comment by SimonSimCity** [comment]
It seems like meteor changed the way of loading the extensions. I've added a `console.log()` to your [`shallInstrumentServerScript`](https://github.com/serut/meteor-coverage/blob/master/server/services/instrumenter.js#L110) function which wasn't called a single time. After searching through the changes, I discovered a method-call of `vm.runInThisContext()` in `tools/static-assets/server/boot.js` and added some logging there.

There were quite some changes on this file, most notably one, [introduced with the node-debugger](https://github.com/meteor/meteor/commit/8550412bb0eaa3b80ae8725f3bed128d629b9d61#diff-e85840f89d0889ea2a4034009dbccc05R356). If you follow closely, you'll see why.

In the new code, the function, returned by `vm.runInThisContext()` is passed to an array and executed after all the modules are loaded. This (in return) has the effect, that `meteor-coverage` - as it is a normal meteor module - only is initialized after every module is loaded (using `vm.runInThisContext()`).

But this is not the only thing that needs to be changed ... The changes in [this commit](https://github.com/meteor/meteor/commit/f244a5b0c63a7e2b961894db2260b6f9e0de08f6) also need to be reverted or rewritten, because the package `istanbul-api` doesn't support using `vm.Script.runInThisContext()` yet.

I can confirm that it works after changing these two parts of `boot.js` in Meteor. No changes needed on his plugin.

**Comment by serut** [comment]
Can you try to replace 
```
    var func = require('vm').runInThisContext(wrapped, {
      filename: scriptPath,
      displayErrors: true
    });
```
instead of 
```
    var script = new (require('vm').Script)(wrapped, {
      filename: scriptPath,
      displayErrors: true
    });

    var func = script.runInThisContext();
```

I think too that this is related to https://github.com/meteor/meteor/commit/f244a5b0c63a7e2b961894db2260b6f9e0de08f6

**Comment by SimonSimCity** [comment]
Doesn't work ... I tried it. And the main reason for that (I guess) is the implementation of `istanbul-api` (https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-hook/lib/hook.js#L137) which expects the second argument to be the filename.

**Comment by serut** [comment]
Nice catch. There is an open PR https://github.com/istanbuljs/istanbuljs/pull/99/files that wants to fix that issue. In that case the only error on the Meteor side is just to use `require('vm').Script.runInThisContext()`

**Comment by SimonSimCity** [comment]
But as I described here, this seems just to be half of what's needed to be done in order to get it working: See my second point on https://github.com/meteor/meteor/issues/9281

**Comment by serut** [comment]
No, I tried again and I don't need any modification of the meteor `boot.js` file. 

I rollback my file to the [original one](https://raw.githubusercontent.com/meteor/meteor/master/tools/static-assets/server/boot.js), added a log `console.error("ME", scriptPath)` and the log is fine : 
```
> meteor test --settings settings.coverage.json --driver-package practicalmeteor:mocha

[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
W20171112-13:43:48.018(1)? (STDERR) ME packages\meteor.js
W20171112-13:43:48.452(1)? (STDERR) ME packages\meteor-base.js
W20171112-13:43:48.453(1)? (STDERR) ME packages\mobile-experience.js
W20171112-13:43:48.453(1)? (STDERR) ME packages\npm-mongo.js
W20171112-13:43:48.455(1)? (STDERR) ME packages\ecmascript-runtime.js
W20171112-13:43:48.455(1)? (STDERR) ME packages\modules-runtime.js
W20171112-13:43:48.456(1)? (STDERR) ME packages\modules.js
W20171112-13:43:48.457(1)? (STDERR) ME packages\ecmascript-runtime-server.js
W20171112-13:43:48.458(1)? (STDERR) ME packages\babel-compiler.js
W20171112-13:43:48.459(1)? (STDERR) ME <windows path>\AppData\Local\Temp\meteor-test-runpu60il.fh2g\.meteor\local\build\programs\server\packages\ecmascript.js
```

**Comment by SimonSimCity** [comment]
@serut That is true - means it loads in these files; well - kind-of. The files actually never end up in the report later on.

In the mid of all these messages I also found this one:

```
W20171129-10:36:50.376(4)? (STDERR) Module load hook: transform [/private/var/folders/ky/vp_prm4178x_yhbb7nydy5dh0000gn/T/meteor-test-runerfyq.noskyb/.meteor/local/build/programs/server/app/app.js]
W20171129-10:36:50.425(4)? (STDERR) Transformation error for /private/var/folders/ky/vp_prm4178x_yhbb7nydy5dh0000gn/T/meteor-test-runerfyq.noskyb/.meteor/local/build/programs/server/app/app.js ; return original code
W20171129-10:36:50.425(4)? (STDERR) Data must be a string or a buffer
W20171129-10:36:50.426(4)? (STDERR) TypeError: Data must be a string or a buffer
W20171129-10:36:50.426(4)? (STDERR)     at Hash.update (crypto.js:99:16)
W20171129-10:36:50.426(4)? (STDERR)     at genVar (/Volumes/WebDocuments/my-project/.meteor/local/isopacks/lmieulet_meteor-coverage/npm/node_modules/istanbul-lib-instrument/dist/visitor.js:33:10)
W20171129-10:36:50.427(4)? (STDERR)     at new VisitState (/Volumes/WebDocuments/my-project/.meteor/local/isopacks/lmieulet_meteor-coverage/npm/node_modules/istanbul-lib-instrument/dist/visitor.js:44:24)
W20171129-10:36:50.427(4)? (STDERR)     at programVisitor (/Volumes/WebDocuments/my-project/.meteor/local/isopacks/lmieulet_meteor-coverage/npm/node_modules/istanbul-lib-instrument/dist/visitor.js:550:22)
W20171129-10:36:50.427(4)? (STDERR)     at Instrumenter.instrumentSync (/Volumes/WebDocuments/my-project/.meteor/local/isopacks/lmieulet_meteor-coverage/npm/node_modules/istanbul-lib-instrument/dist/instrumenter.js:126:44)
W20171129-10:36:50.427(4)? (STDERR)     at /Volumes/WebDocuments/my-project/.meteor/local/isopacks/lmieulet_meteor-coverage/npm/node_modules/istanbul-lib-hook/lib/hook.js:29:31
W20171129-10:36:50.428(4)? (STDERR)     at Object.vm.runInThisContext (/Volumes/WebDocuments/my-project/.meteor/local/isopacks/lmieulet_meteor-coverage/npm/node_modules/istanbul-lib-hook/lib/hook.js:146:19)
W20171129-10:36:50.428(4)? (STDERR)     at /private/var/folders/ky/vp_prm4178x_yhbb7nydy5dh0000gn/T/meteor-test-runerfyq.noskyb/.meteor/local/build/programs/server/boot.js:392:30
W20171129-10:36:50.428(4)? (STDERR)     at Array.forEach (<anonymous>)
W20171129-10:36:50.428(4)? (STDERR)     at Function._.each._.forEach (/Users/simon/.meteor/packages/meteor-tool/.1.6.0.1vkwqrb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)

**Comment by serut** [comment]
If I'm right, `/private/var/folders/ky/vp_prm4178x_yhbb7nydy5dh0000gn/T/meteor-test-runerfyq.noskyb/.meteor/local/build/programs/server/app/app.js` is your entire server app code, and when it tries to instrument it, it uses the current implementation of istanbuljs, which fails to retrieve the content of the file.

On the other hand, if there was an issue with Meteor and `new (require('vm').Script)`, istanbuljs would not be called at all, no ?

**Comment by SimonSimCity** [comment]
@serut As I wrote: When I start off with a clean installation and apply the changes from the PR, IstanbulJS is never called.

Only after again applying the changes I noted in https://github.com/meteor/meteor/issues/9281, I got the exception I noted before, which comes from an incompatibility from this extension towards the changes of the library IstanbulJS, if I remember it correctly.

I'll run another test now the days to come in order to get it right again, including the latest changes on the IstanbulJS library.

**Comment by SimonSimCity** [comment]
So, now I've analyzed it all:

You can freely update the IstanbulJS library to the new version as you did in https://github.com/serut/meteor-coverage/pull/57. This on it's own - even though - is not the game changer, but opens up for https://github.com/istanbuljs/istanbuljs/pull/99 which (finally) will make the call of `runInThisContext()` compatible to the latest version of NodeJS. This then will need https://github.com/serut/meteor-coverage/pull/60 to be merged.

The changes I wrote in https://github.com/meteor/meteor/issues/9281 are still required. The only difference is, that (after https://github.com/istanbuljs/istanbuljs/pull/99 got merged) we can use your version: https://github.com/serut/meteor-coverage/issues/54#issuecomment-341123076

**Comment by SimonSimCity** [comment]
Just for the record:

The changes I suggested to Meteor just got released in v1.6.1 🎉  The only outstanding changes now are those to `istanbuljs` ...

**Comment by serut** [comment]
Just merged all these PR. But I don't have my laptop to publish libraries, you will need to wait a little bit more... I will do it ASAP.
On another hand, spacejam is not working as smooth as before. As you said in the PR I've closed, only users that does not use coffeescript 2.0 will be able to use practicalmeteor:mocha, but spacejam requires practicalmeteor:mocha-console-runner to properly run. What a nightmare... Would be nice to get another test runner that supports this library.

**Comment by SimonSimCity** [comment]
I've mentioned it in the PR as well, there is a PR by me waiting on the `meteortesting:mocha` package: https://github.com/meteortesting/meteor-mocha/pull/51

But what would be nice is if we could use `nyc` by any chance or at least something that's more generally usable than hooking into the very inner being of file-loading.

If you ask me, this ticket is closed as soon as you've published a new version. Everything else belongs to a different ticket or library.

Just for the record: Using `spacejam` including the other libs will work on Meteor 1.6.0, because they first switched to the newer version of `coffeescript` in Meteor 1.6.1 😉

**Comment by SimonSimCity** [comment]
Should we somewhere leave a comment that server side coverage on Meteor 1.6.0 and 1.6.0.1 are not supported by this package due to https://github.com/meteor/meteor/issues/9281?

**Comment by serut** [comment]
The Meteor constraint is pretty clear (`package.js`): 
`  api.versionsFrom('METEOR@1.6.1');`

nyc can't be used, that's the idea of this repository. nyc waits the called process to die to export coverage, whether this package provides an API to export coverage reports. 

I've published the version, but tests are not working anymore. Can you look at it ?

**Comment by SimonSimCity** [comment]
@serut I've now tried it myself:

When updating the package `lmieulet:meteor-coverage` to 2.0.0 in my project, it fails. What wonders me is, that it works if I take the code from this repository at the state where you raised the version.

I've diffed the files downloaded from the meteor-atmosphere to the ones from this repo. The only difference is in the `node_modules` folder.

Could you please try uploading the version once more? Make sure ...:
1. Running `meteor --version` in the directory of the plugin returns `v1.6.1`
2. To run `meteor npm install` in the directory after ensuring that `meteor --version` reports the correct version in order to bundle it with the correct NPM packages

**Comment by SimonSimCity** [comment]
@serut could you try removing the `node_modules` folder before publishing it and trying it again? It at least was a valid work-around for the issue linked here. Could you try it?

Then please also commit the content of the `.npm` folder created while publishing, because these files actually contains the `package-lock.json` file this package was published with.

Which actually gives me the idea to remove `package.json` and `package-lock.json` from your repo because meteor will create the actual `package-lock.json` in your `.npm` folder and take your `package.js` as basis to generate the `package.json` to be used.

**Comment by serut** [comment]
No, the `package.json`isn't generated at all, so if I remove it, I will loose its content forever. And if I don't commit the `package-lock.json` you won't get any constraint issue. I don't think your issue is related to some package file.

I will clone the repo, launch tests, publish it and let you know.

**Comment by serut** [comment]
That's published

**Comment by SimonSimCity** [comment]
Yes, works for me 😃🎉
