### ISSUE TITLE
SyntaxError on lmieulet_meteor-coverage.js:300

### ISSUE THREAD

**Issue by Szayet** [serut/meteor-coverage#59]
By using ` meteor test --driver-package=practicalmeteor:mocha --settings=settings/settings.coverage.json --port=3100` when visiting the mocha test runner (`http://localhost:3100/`) the server drops the following error:
```
meteor://💻app/packages/lmieulet_meteor-coverage.js:300
W20171126-21:56:57.646(1)? (STDERR)           /* istanbul ignore else */if (err) throw err;
W20171126-21:56:57.646(1)? (STDERR)                                              ^
W20171126-21:56:57.647(1)? (STDERR)
W20171126-21:56:57.647(1)? (STDERR) SyntaxError: Unexpected token, expected ; (1:10)
```

## Expected Behavior
No error, and coverage statistics for the tests

## Current Behavior
Got the error above and `http//localhost:3100/coverage`  shows the following message: 
`No coverage information has been collected`

## Your Environment
* Version used: latest 1.1.4 (just installed)
* Environment name and version: Meteor 1.6, boundled npm V.5.4.2
* Operating System and version: Ubuntu 16.0.4.3 LTS

**Comment by serut** [comment]
Hello ! Thanks for submitting an issue. 
meteor-coverage is not ready for Meteor 1.6 for now, as there is a breaking change on the Meteor server core. We are waiting that the coverage library make its change before trying again.

Do you have a reproducable environment available ?

**Comment by serut** [comment]
We've finished to work on Meteor 1.6. Feel free to test with your app, you should not have any issue.
