### ISSUE TITLE
[Question] dispatch:mocha-phantomjs Client coverage report

### ISSUE THREAD

**Issue by firrae** [serut/meteor-coverage#6]
Hey there,

Looking at your example I'm not 100% sure I understand if you can get the coverage report out of the dispatch:mocha-phantomjs test driver? It seems like only using spacejam and the practicalmeteor packages accomplish this. Is this correct or am I missing something?

**Comment by serut** [comment]
Yes you are correct, it only works with spacejam right now : I cloned spacejam and added a new phantomjs runner that saves the coverage when tests are done. Here is the commit that adds coverage to spacejam https://github.com/serut/spacejam/commit/bac57102ed126ebde2887255cef5dbadff1dbd92.

I think it's doable with `dispatch:mocha-phantomjs`, but it would need to find out a way to send parameters (the type of import / output) and a way to launch my package

**Comment by firrae** [comment]
Hm, fair enough, I'll play with spacejam a bit, I had hoped to stay away from relying on another package but it seems like it's the only way to satisfy my thirst for coverage reports.

**Comment by firrae** [comment]
Follow up, does this method also get the client files as well?

**Comment by serut** [comment]
Yes it saves the client and the server coverage, it can also merge coverage between test runs
