### ISSUE TITLE
Find a way to automatically set the app-path

### ISSUE THREAD

**Issue by SimonSimCity** [serut/meteor-coverage#61]
I currently don't have a windows environment, but on Mac, `process.env.PWD` returned the desired value. Could we not get this somewhere tested and replace it by this value?

**Comment by serut** [comment]
That's the issue. I develop this package on all environments and `process.env.PWD` inside the package refers to the tmp folder where your app have been compiled on Windows. (something like `C/user/yourself/app_bullshit/meteor/tmp/[....]`).  
That's maybe not an issue anymore on the last version of Meteor.  
My favorite workaround is to provide that value from the headless browser runner on runtime as I did with spacejam.

**Comment by SimonSimCity** [comment]
True ... even https://github.com/VeliovGroup/Meteor-root doesn't work anymore ...
