### ISSUE TITLE
Confusion about using web coverage report

### ISSUE THREAD

**Issue by noahsw** [serut/meteor-coverage#7]
I can get the report up and running using:
```
COVERAGE=1 \
COVERAGE_VERBOSE=1 \
COVERAGE_APP_FOLDER=/path/to/your/meteor/app/ meteor
```

But it doesn't seem to be based on my *test* coverage. It's only based on the app loading.

How can I have my tests run and then view the web coverage report?

I tried running `COVERAGE=1 COVERAGE_VERBOSE=1 COVERAGE_APP_FOLDER=${PWD/#$HOME/~}/ meteor test --driver-package practicalmeteor:mocha` but that didn't do the trick.

Thx!

**Comment by serut** [comment]
> But it doesn't seem to be based on my test coverage. It's only based on the app loading.

When you cover an app, every code executed on the server side will be marked as executed, whether it's a test or an human that runned that code. For the client side it's the same idea but it requires to send the client coverage to the server.

`COVERAGE_APP_FOLDER=${PWD/#$HOME/~}/` must be the root folder of your meteor app or it will fail to find out your real file. 

> How can I have my tests run and then view the web coverage report?

It's not easy. You need to open your test page, wait that all your test are done, send the coverage (Meteor.sendCoverage...) and at that moment you can open the /coverage page.   
Another solution is to use CI to do that job, you will see your coverage report on a coveralls like platform.    
The easiest way is not implemented yet. It would be to use spacejam and a new type of export, something like that:

`spacejam .... --coverage='out_html'`

In fact, there are so many export type that are not supported https://github.com/serut/meteor-coverage#meteorexportcoveragetype-callback . Sorry if this project is not ready to use as you wanted.

**Comment by serut** [comment]
You can now export to html format. I close the issue

**Comment by noahsw** [comment]
Meaning `--coverage='out_html'` works now?

**Comment by serut** [comment]
Yes !  Look at the meteor forum to see the changelog. The teamcity report is not working, but others are now.  I need to update the readme + create a changelog for this repo
You need to update my spacejam fork btw
