### ISSUE TITLE
jquery package dependecies not loaded 

### ISSUE THREAD

**Issue by obonyojimmy** [serut/meteor-coverage#78]
Jquery dependency not loaded on client side

http://localhost:3000/packages/lmieulet_meteor-coverage.js?hash=1d48273b7dd15a2c52d3ca3914a49eae979cbd1f

**Comment by serut** [comment]
Hello,

This package does not depend on the jquery dependency, so I don't think your problem is linked to this lib !

**Comment by xolott** [comment]
I just reported this issue on #88 and it is triggered by this package.
